In [1]:
# numpy is similar to list 
import numpy as np
a = np.array([4,4,4,4,4])
a

array([4, 4, 4, 4, 4])

In [6]:
b = np.array([[3,4,5,6], [3,5,8,4],[3,4,5,6]])
b

array([[3, 4, 5, 6],
       [3, 5, 8, 4],
       [3, 4, 5, 6]])

In [7]:
type(a)

numpy.ndarray

In [8]:
len(a)

5

In [9]:
b[0: ]

array([[3, 4, 5, 6],
       [3, 5, 8, 4],
       [3, 4, 5, 6]])

In [11]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [12]:
y = np.arange(2,20)
y

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
z= np.arange(3 ,5 ,2)
z

array([3])

In [19]:
i = np.ones(5, dtype = np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [20]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((4,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [24]:
len(price)

3

In [25]:
type(price)

numpy.ndarray

In [27]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np.linspace(1,100, num = 9)

array([  1.   ,  13.375,  25.75 ,  38.125,  50.5  ,  62.875,  75.25 ,
        87.625, 100.   ])

In [34]:
np.ones(50, dtype= np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [35]:
np.zeros(100, dtype= np.float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Array functions in python 


In [36]:
a = np.array([2.4,56.3,3.5,6.8,9.4,9.3])
a

array([ 2.4, 56.3,  3.5,  6.8,  9.4,  9.3])

In [38]:
a.sort()
a

array([ 2.4,  3.5,  6.8,  9.3,  9.4, 56.3])

In [39]:
b= np.array([100,45,67,23,98,12,43,65,87,23,21])
b

array([100,  45,  67,  23,  98,  12,  43,  65,  87,  23,  21])

In [40]:
b.sort()
b

array([ 12,  21,  23,  23,  43,  45,  65,  67,  87,  98, 100])

In [42]:
# concatenate the two arrays

c= np.concatenate((a,b))
c

array([  2.4,   3.5,   6.8,   9.3,   9.4,  56.3,  12. ,  21. ,  23. ,
        23. ,  43. ,  45. ,  65. ,  67. ,  87. ,  98. , 100. ])

In [43]:
c.sort()
c

array([  2.4,   3.5,   6.8,   9.3,   9.4,  12. ,  21. ,  23. ,  23. ,
        43. ,  45. ,  56.3,  65. ,  67. ,  87. ,  98. , 100. ])

In [44]:
# 2-D array

a= np.array([[1,2,3,4,5],[6,7,8,9,0]])
a

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [45]:
b= np.array([[3,4,5,6,7],[2,3,4,5,6]])
b 

array([[3, 4, 5, 6, 7],
       [2, 3, 4, 5, 6]])

In [46]:
c= np.concatenate((a,b))
c

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [3, 4, 5, 6, 7],
       [2, 3, 4, 5, 6]])

## Reshpe the array into row and column

In [4]:
import numpy as np
a= np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
x = np.arange(16)
x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
u = x.reshape(4,4)
u

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
a= np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
b = a[np.newaxis, : ]
b

array([[1, 2, 3, 4, 5, 6, 7]])

In [19]:
b = a[:,np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])